### PR TITLE
feat(contributing.md): init guidelines

### PR DESCRIPTION
**Pull request by macintoshpie**

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
Jenkins Build 6 : time taken 25 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 7 : time taken 36 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 8 : time taken 29 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 9 : time taken 28 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 10 : time taken 1 hr 20 min

**Review by themarcelor — APPROVED** [review]
+1

**Pull request merged**
