### PR TITLE
fixing the study-viewer test for Jenkins env

### PR DESCRIPTION
**Pull request by atharvar28**
Updating the test for supporting jenkins env which does not display the `Download Button`

So to display the `Download Button`, `FileDataType` needs to be configured in the `studyViewerConfig` in gitops.json. But currently on Jenkins env, it is not configured. 

So this PR is mitigating the issue by checking the requestor request_id status by using the endpoint `GET requestor/request/<request_id>`

### CODE REVIEW

**Review by themarcelor — APPROVED** [review]
+1

**Review by haraprasadj — APPROVED** [review]
+1

**Comment by paulineribeyre** [comment]
for context ---- can't have download button in jenkins without having a `fileDataType` index configured

**Review by paulineribeyre — APPROVED** [review]

**Review by themarcelor — APPROVED** [review]
+1

**Review by haraprasadj — APPROVED** [review]
+1

**Pull request merged**
