### PR TITLE
fix(qa): skip submission page check for midrc

### PR DESCRIPTION
**Pull request by jingh8**
quick fix for midrc

### CODE REVIEW

**Review by mfshao — COMMENTED** [review]
any reason why we don't to this in `runTest.sh`?

**Comment by jingh8** [comment]
There is a concern for test coverage for midrc. If we do it in `runTest.sh` , midrc will skip whole dataUpload test suite. But now at least it tests dataUpload through api.

**Review by themarcelor — APPROVED** [review]
+1

**Comment by themarcelor** [comment]
Hi @jingh8 @mfshao , exactly. I feel we should try to run, at least, some of the steps for test coverage purposes.
If the absence of that button is the only blocker, we could skip these steps and still test the file upload components (`ssjdispatcher`, `indexs3client`, `fence` Upload PreSigned URL, etc. etc.).

**Pull request merged**
