### PR TITLE
Feat/data-upload WIP

### PR DESCRIPTION
**Pull request by paulineribeyre**
/!\ WIP

### CODE REVIEW

**Comment by paulineribeyre** [comment]
All the tests pass locally. This is what is left to do so that they will pass here:
- delete from S3 all the files uploaded during the tests. how to do this without access to the aws creds in fence-config? or how to access the creds?
- set up the s3 listener in jenkins-niaid, jenkins-dcp and jenkins-brain.
- make a new release of the gen3-client that includes the new upload command and the fix to the config command. set up jenkins so that the executable is in the homedir.
- right now, the gen3-client `download` function does not save under the specified filePath, but under the actual file name: to investigate and fix.
- after the new upload role is added to arborist/fence, give that role to `cdis.autotest@gmail.com` in commons-users. do not give it to `dummy-one` and `smarty-two` because we need to test with users that don't have access.

**Comment by PlanXCyborg** [comment]
Jenkins Build 25 : time taken 57 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 26 : time taken 5 min 25 sec

**Comment by PlanXCyborg** [comment]
Jenkins Build 27 : time taken 1 min 49 sec

**Comment by PlanXCyborg** [comment]
Jenkins Build 28 : time taken 13 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 29 : time taken 1 min 51 sec

**Comment by PlanXCyborg** [comment]
Jenkins Build 30 : time taken 10 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 31 : time taken 30 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 32 : time taken 56 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 33 : time taken 15 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 35 : time taken 34 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 36 : time taken 40 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 38 : time taken 44 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 39 : time taken 25 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 40 : time taken 47 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 41 : time taken 53 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 42 : time taken 28 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 43 : time taken 57 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 44 : time taken 47 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 42 : time taken 10 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 43 : time taken 26 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 45 : time taken 21 sec

**Comment by PlanXCyborg** [comment]
Jenkins Build 44 : time taken 11 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 46 : time taken 24 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 47 : time taken 21 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 48 : time taken 26 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 49 : time taken 33 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 50 : time taken 23 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 51 : time taken 23 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 52 : time taken 23 min

**Pull request merged**
