### PR TITLE
check the popup box by the accept button

### PR DESCRIPTION
**Pull request by jingh8**
The popup box of user agreement for MIDRC and VA have different text. To click the Accept button properly, change the code to find if there is a popup box contains the accept button.

### CODE REVIEW

**Review by haraprasadj — COMMENTED** [review]
The reason for using this was to ensure that the popup that shows up is the Data Use Agreement and not some random popup. Do we want to lose that information?

**Comment by jingh8** [comment]
If we want to keep that, we can add the text of va popup box to the check also.
"VA systems are intended for Academic and Institutional Users"

**Comment by haraprasadj** [comment]
> If we want to keep that, we can add the text of va popup box to the check also. "VA systems are intended for Academic and Institutional Users"

Ok, maybe a more important question is why we cannot have a standard title for data use agreement pop ups across projects 🤷🏼‍♂️

**Comment by m0nhawk** [comment]
> > If we want to keep that, we can add the text of va popup box to the check also. "VA systems are intended for Academic and Institutional Users"
> 
> Ok, maybe a more important question is why we cannot have a standard title for data use agreement pop ups across projects 🤷🏼‍♂️

Each institution will have its own data use agreement, we can't really on it being the same.

Even in QA we should have the environment as close as possible to production.

**Comment by jingh8** [comment]
What about including "Use Agreement" phrase in the title such as this pr: https://github.com/uc-cdis/cdis-manifest/pull/3768/files

**Comment by mfshao** [comment]
For this `systemUseMsg` test we should not hard code them for either VA ori MIDRC or other envs, the test should be generic enough and env independent

We should be able to alter the locater value based on portal config we ingested into the test

**Comment by m0nhawk** [comment]
We should definitely not hardcode it, especially that for most of the projects it's something we need to have "as-is", without any modifications.

**Comment by haraprasadj** [comment]
> > > If we want to keep that, we can add the text of va popup box to the check also. "VA systems are intended for Academic and Institutional Users"
> > 
> > 
> > Ok, maybe a more important question is why we cannot have a standard title for data use agreement pop ups across projects 🤷🏼‍♂️
> 
> Each institution will have its own data use agreement, we can't really on it being the same.
> 
> Even in QA we should have the environment as close as possible to production.

I am not referring to the message in the popup, but the title in the popup itself

**Comment by m0nhawk** [comment]
By "data use agreement" I meant both title & text. We shouldn't change any of it.

**Comment by haraprasadj** [comment]
> For this `systemUseMsg` test we should not hard code them for either VA ori MIDRC or other envs, the test should be generic enough and env independent
> 
> We should be able to alter the locater value based on portal config we ingested into the test

We do have a mechanism to use custom locators like this - https://github.com/uc-cdis/gen3-qa/blob/master/utils/apiUtil.js#L434

The question was more from the portal design perspective, why we cannot standardize the titles of popups like we do for page names

**Comment by haraprasadj** [comment]
> By "data use agreement" I meant both title & text. We shouldn't change any of it.

Hmm ... the locator does not have to be visible text, we should have a way to recognise Data Use Agreement pop up uniquely across implementations, maybe a class name or something else. Otherwise the test code becomes more and more unwieldy and harder to read. I know this is not a current concern, so if we want to deal with it later, it is ok.

**Review by haraprasadj — APPROVED** [review]

**Review by haraprasadj — APPROVED** [review]
+1

**Pull request merged**
